name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pytest --cloud-api-key ${{ secrets.CLOUD_API_KEY }}
